name: consumatron
description: Tracking your finances so you can consume more.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 "

dependencies:
  
  flutter:
    sdk: flutter
    
  json_annotation: ^4.0.1

  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^4.1.3




flutter:

  uses-material-design: true

  fonts:
    - family: Gugi
      fonts:
        - asset: assets/fonts/Gugi-Regular.ttf

  
